### ISSUE TITLE
Comments not working

### ISSUE THREAD

**Issue by vinnieg** [estan/protoc-gen-doc#15]
I can't get the comments to show up in the description field on Windows.  I've tried using protoc version 2.6.1 and version 3.0.  They don't show up in any output type.  Any ideas?

Thanks

**Comment by estan** [comment]
That's strange. Could you give an example of a `.proto` file that you are using where you have this problem? Are you sure you're using documentation comments (`/// ...` or `/** ... */), and not regular comments (`//` or `/* .. */`)? Are you using a released version or the `master` branch from Git?

**Comment by estan** [comment]
I just tried both [version 0.7](https://github.com/estan/protoc-gen-doc/releases/tag/v0.7) and [the latest Windows build of master](https://ci.appveyor.com/project/estan/protoc-gen-doc/build/artifacts) against the [example .proto files](https://github.com/estan/protoc-gen-doc/tree/master/examples/proto) on Windows XP and it seems to work in both cases:

![Version 0.7 on Win XP](http://dose.se/~estan/winxp-0.7.png "On Windows XP with version 0.7")

![Version winxp-0.7-75-g847f592.png on Win XP](http://dose.se/~estan/winxp-0.7-75-g847f592.png "On Windows XP with latest build from master")

**Comment by vinnieg** [comment]
Oops. I wasn't using the correct comment format.  I thought I had read that the '///' was for file comments.  And i had originally used the original port from 2013.

Thanks!

**Comment by estan** [comment]
Aha. Yes, the tool parses only `/// ...` and `/** ...*/`, similar to e.g. Doxygen and JavaDoc, to allow "non-documentation" comments with just `/* ... */` and `// ...`.

**Comment by estan** [comment]
Aha, with "original port from 2013" you mean https://code.google.com/archive/p/protoc-gen-docbook/ ? Yes, that's another project (unmaintained I think), separate from this. It seems it used just `//` and `/** .. */`.
