### ISSUE TITLE
make fails on OSx Yosemite

### ISSUE THREAD

**Issue by sriv** [estan/protoc-gen-doc#2]
I tried the instructions listed for Mac:

```
INb:protoc-gen-doc steam$ export PROTOBUF_PREFIX=/usr/local/Cellar/protobuf/2.6.1/
INb:protoc-gen-doc steam$ qmake
/Users/steam/projects/gauge/protoc-gen-doc/protoc-gen-doc.pro:22: Unknown replace function: getenv
Project ERROR: You must set the PROTOBUF_PREFIX environment variable!
INb:protoc-gen-doc steam$ echo $PROTOBUF_PREFIX
/usr/local/Cellar/protobuf/2.6.1/
INb:protoc-gen-doc steam$
```

Despite setting the `PROTOBUF_PREFIX` value, it still complains about it.

Any tips?

**Comment by sriv** [comment]
Figured this out, I had a conflict between Qt4 and Qt5, and `qmake` picked up Qt4 version, which is incompatible. [This Stackoverflow answer](http://stackoverflow.com/a/28509231/326543) helped me setup Qt5 correctly. 

And now it works fine.

**Comment by estan** [comment]
Hmf, the issue notification got buried in my mail. Glad you figured it out. I guess I should add an explicit check for the Qt version, and give a good error message.

**Comment by estan** [comment]
Added a check with e9c4d2d3473c8c9fe06ec2e9917a64620d54f1fc.

**Comment by sriv** [comment]
:+1:
