### ISSUE TITLE
any more detailed instruction how to install on Mac?

### ISSUE THREAD

**Issue by guozheng** [estan/protoc-gen-doc#20]
I am trying to install this on Mac OSX, searched qmake through HomeBrew, but could not find it. Can someone give more detailed instructions?

Currently, the doc says:
```
    $ export PROTOBUF_PREFIX=/path/to/protobuf-2.6.1
    $ qmake
    $ make
```

**Comment by estan** [comment]
Hi @guozheng ,

`qmake` is part of Qt. One of the build requirements is Qt 5 (see top of https://github.com/estan/protoc-gen-doc/blob/master/BUILDING.md). You can install this however you want, but I suggest `qt5` via Homebrew.

If you need even more detailed instructions, you can look at the Travis build file (https://github.com/estan/protoc-gen-doc/blob/master/.travis.yml). The tool is built and tested regularly on Mac OS X, and that file contains the exact steps.

In short, to get the dependencies from Homebrew:

```
brew update
brew install qt5 protobuf
brew link --force qt5
export PROTOBUF_PREFIX=$(brew --prefix protobuf)
```

and then build the tool:

```
git clone git@github.com:estan/protoc-gen-doc.git
cd protoc-gen-doc
qmake
make
```

Copy the resulting `protoc-gen-doc` executable to where you want it, but it must be in `PATH` for the `protoc` compiler to find it, or be specified with `--plugin` (explained in `README.md`).

Hope this helps.

**Comment by sumancholleti** [comment]
hi i tried above steps but how do i get html from PROTO

when i say qmake it says could not resolve sdk path for macosx,Please help

**Comment by estan** [comment]
@sumancholleti: I don't have access to a Mac myself, so I can't test. But, how did you install Qt?
