### ISSUE TITLE
Support for HTML links inside comments

### ISSUE THREAD

**Issue by windsource** [estan/protoc-gen-doc#203]
I am using `protoc-gen-doc` to generate HTML documentation. I would like to add HTML links in the comments that appear as clickable links in the documentation.

Example:

```
required int64 myValue = 1;  /// More info on http://www.google.com
```

Unfortunately the link is not clickable in the resulting documentation. So I tried to add HTML code in the comment like

```
required int64 myValue = 1;  /// More info on <a href="http://www.google.com">Google</a>
```

but that gets escaped and also does not work.

Is there any other way in order to get clickable links?

**Comment by booelean** [comment]
In the mustache documentation at  //mustache.github.io/mustache.5.html.

**Comment by booelean** [comment]
In the mustache documentation at //mustache.github.io/mustache.5.html.

All variables are HTML escaped by default. If you want to return unescaped HTML, use the triple mustache: {{{name}}}.

You can also use & to unescape a variable: {{& name}}. This may be useful when changing delimiters (see "Set Delimiter" below).

**Comment by booelean** [comment]
From the mustache documentation at //mustache.github.io/mustache.5.html

All variables are HTML escaped by default. If you want to return unescaped HTML, use the triple mustache: {{{name}}}.
You can also use & to unescape a variable: {{& name}}. This may be useful when changing delimiters (see "Set Delimiter" below).

**Comment by windsource** [comment]
Thanks for the answer. But I think using this method I can only switch off escaping for the whole comment, not only for links. Is there a way to detect that a part of the comment is an HTML link and switch off escaping just for that part?

**Comment by estan** [comment]
I'm afraid this is not really possible, short of the tool automatically detecting links in the comment text and doing the link-ification of them. But this can't really work, since the tool can't know if the output is HTML or not (a custom template may be used) :/

I'm afraid you'll have to use {{{ }}} in your custom template, to turn off automatic escaping, and then make sure you do any escaping needed manually.
