### ISSUE TITLE
Support JSON output

### ISSUE THREAD

**Issue by InfinitiesLoop** [estan/protoc-gen-doc#210]
It's great that the tool can generate various doc formats. But we need to actually _do_ something with the docs, so we need them in a machine readable format. I'm trying to craft a mustache template that outputs JSON, but generating _valid_ JSON that way is going to be tricky and probably require me to do some post-processing on what is generated.

**Comment by wangming1993** [comment]
@estan Same requirements, thx

**Comment by johndpope** [comment]
this could be achieved by hacking this parser

My initial approach would be to get the grammar file for protobuffer / .g4 file - then bang it into antlr to spitout appropriate files.
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#safe=off&q=antlr+grammar+g4+++proto+file

This guy has this
https://github.com/yesme/protobuf-parser

there's also 
https://github.com/protobufel/protobuf-el

    // generate the AST tree
    CommonTree tree = (CommonTree) result.getTree();

    // trace the tree
    if (SampleParser.showTrace) {
      SampleParser.trace(tree, 0);
}

once you have the ast tree - you'll have all the methods / attributes etc.

**Comment by johndpope** [comment]
you maybe able to grab this file
https://github.com/johndpope/protobuf-parser/blob/master/dsl/ProtoParser.g
then throw it at antlr - then you'd have a parser in any language

then call ast2json
http://stackoverflow.com/questions/32428108/convert-python-ast-to-json-and-back

if this work is incorporated into library - then it'd make it more powerful.
Or create another library? you could go
protoc-gen-ast

or have output format as ast_json

**Comment by estan** [comment]
Sorry it took so long. Support for JSON output has now been added, and a new release 0.9 has been made.
