### ISSUE TITLE
Enhancement - detect comments

### ISSUE THREAD

**Issue by johndpope** [estan/protoc-gen-doc#255]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/example/example.proto

spits out - 

`# Protocol Documentation
<a name="top"/>

## Table of Contents
* [example.proto](#example.proto)
 * [Example](#tensorflow.Example)
 * [SequenceExample](#tensorflow.SequenceExample)
* [Scalar Value Types](#scalar-value-types)

<a name="example.proto"/>
<p align="right"><a href="#top">Top</a></p>

## example.proto

<a name="tensorflow.Example"/>
### Example

| Field | Type | Label | Description |
| ----- | ---- | ----- | ----------- |
| features | [Features](#tensorflow.Features) | optional |  |

<a name="tensorflow.SequenceExample"/>
### SequenceExample

| Field | Type | Label | Description |
| ----- | ---- | ----- | ----------- |
| context | [Features](#tensorflow.Features) | optional |  |
| feature_lists | [FeatureLists](#tensorflow.FeatureLists) | optional |  |

<a name="scalar-value-types"/>
## Scalar Value Types

| .proto Type | Notes | C++ Type | Java Type | Python Type |
| ----------- | ----- | -------- | --------- | ----------- |
| <a name="double"/> double |  | double | double | float |
| <a name="float"/> float |  | float | float | float |
| <a name="int32"/> int32 | Uses variable-length encoding. Inefficient for encoding negative numbers – if your field is likely to have negative values, use sint32 instead. | int32 | int | int |
| <a name="int64"/> int64 | Uses variable-length encoding. Inefficient for encoding negative numbers – if your field is likely to have negative values, use sint64 instead. | int64 | long | int/long |
| <a name="uint32"/> uint32 | Uses variable-length encoding. | uint32 | int | int/long |
| <a name="uint64"/> uint64 | Uses variable-length encoding. | uint64 | long | int/long |
| <a name="sint32"/> sint32 | Uses variable-length encoding. Signed int value. These more efficiently encode negative numbers than regular int32s. | int32 | int | int |
| <a name="sint64"/> sint64 | Uses variable-length encoding. Signed int value. These more efficiently encode negative numbers than regular int64s. | int64 | long | int/long |
| <a name="fixed32"/> fixed32 | Always four bytes. More efficient than uint32 if values are often greater than 2^28. | uint32 | int | int |
| <a name="fixed64"/> fixed64 | Always eight bytes. More efficient than uint64 if values are often greater than 2^56. | uint64 | long | int/long |
| <a name="sfixed32"/> sfixed32 | Always four bytes. | int32 | int | int |
| <a name="sfixed64"/> sfixed64 | Always eight bytes. | int64 | long | int/long |
| <a name="bool"/> bool |  | bool | boolean | boolean |
| <a name="string"/> string | A string must always contain UTF-8 encoded or 7-bit ASCII text. | string | String | str/unicode |
| <a name="bytes"/> bytes | May contain any arbitrary sequence of bytes. | string | ByteString | str |
`

but if you look into comments - theres more data/text / comments inside proto file that could be surfaced

**Comment by estan** [comment]
Sorry for the very late reply. The comments in your example are not documentation comments (`///` or `/** ... */`). The tool will only process documentation comments. This is to allow `.proto` authors to use regular `//` and `/* ... */` for comments that should not show up in the documentation.
