### ISSUE TITLE
Support for including all proto files within subdirectories

### ISSUE THREAD

**Issue by patelpareshc** [estan/protoc-gen-doc#266]
At present we need to provide proto files individually or the `package/*.proto` format.
If the project has multiple packages, in different modules, then there is no way to run the protoc on parent directory and say `**/*.proto` to generate documentation for all the proto files.
Not sure if this needs to be at the protoc forum itself..

**Comment by estan** [comment]
I'm afraid you're right in your suspicious, that it has to be brought up on the `protoc` forum. It is the `protoc` compiler itself that parses files given on the command line, and then simply feeds the plugin with a list of data structures corresponding to the parsed files. So a plugin (like `protoc-gen-doc`) has no control over the command line format for input files :(
