### ISSUE TITLE
protoc doc generator issue with MAC OS

### ISSUE THREAD

**Issue by sumancholleti** [estan/protoc-gen-doc#268]
Hello

AM trying to install protoc doc gen

i followed the steps from github steps but i kept getting this below error
protoc-gen-doc: program not found or is not executable
--doc_out: protoc-gen-doc: Plugin failed with status code 1.

**Comment by estan** [comment]
Is the `protoc-gen-doc` executable in your `PATH`?

**Comment by estan** [comment]
I need more information to know what is wrong. The `protoc-gen-doc` executable must be in your `PATH` when running `protoc`, or it will not be able to find the plugin. Did you get an executable when you built? Can you paste the full output from building the plugin?

**Comment by sumancholleti** [comment]
this is the error am getting when i run command qmake

 Could not resolve SDK Path for 'macosx'

**Comment by sumancholleti** [comment]
Hello estan

This is the error am getting 
protoc-gen-doc: program not found or is not executable
--doc_out: protoc-gen-doc: Plugin failed with status code 1.

**Comment by estan** [comment]
Are you sure it's in `PATH`? Can you show the output from `export`?

**Comment by sumancholleti** [comment]
Please find attached

<img width="813" alt="screen shot 2017-03-02 at 9 59 42 am" src="https://cloud.githubusercontent.com/assets/5066446/23512560/fcae1d30-ff2e-11e6-80f5-945f9d32c6ed.png">

**Comment by estan** [comment]
This shows that `protoc-gen-doc` is not in your `PATH`. Your path is set to `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`. It must also contain the directory which holds the `protoc-gen-doc` executable.

**Comment by sumancholleti** [comment]
how do i make it work or change my paths to make it work ,

please help

**Comment by sumancholleti** [comment]
please check now , it still doesnt work
<img width="804" alt="screen shot 2017-03-02 at 10 20 41 am" src="https://cloud.githubusercontent.com/assets/5066446/23513410/f2279780-ff31-11e6-9822-1a6f2af01dd4.png">

**Comment by sumancholleti** [comment]
you know what its working now,
<img width="747" alt="screen shot 2017-03-02 at 10 32 25 am" src="https://cloud.githubusercontent.com/assets/5066446/23513869/8f57be1c-ff33-11e6-8824-2fd1b53a2b47.png">
but i am not able to generate my own proto files,because its saying import is not defined

Also I have addded common.proto in activation.proto

**Comment by estan** [comment]
You might be bumping into https://github.com/estan/protoc-gen-doc/issues/22 . See that issue for more information. In any case, it's not possible for me to debug this without having access to the `.proto` files in question, or at least a detailed description of how they're laid out in the file system and how they're importing each other.

Are you invoking protoc in exactly the same way (same `-I` flags?) as when you are generating sources?

**Comment by sumancholleti** [comment]
also Pdf is throwing this error

which command is the right to generate pdf

fop -xml doc/example.docbook -xsl $(DOCBOOK_XSL) -param use.extensions 0 -param fop1.extensions 1 -param paper.type A4 -param page.orientation landscape -pdf doc/example.pdf


Please find attached proto files

**Comment by estan** [comment]
You did not include the error you got. Besides, generating PDF is not part of protoc-gen-doc. The plugin only generates DocBook XML, and Apache FOP is just one way to turn DocBook XML into PDF.

You did not attach any `.proto` files. I don't think GitHub comments support that file type, so you'll have to find somewhere to upload them. In any case, I'm pretty sure what you're seeing is #22, which is unfixable until the plugin is updated for protobuf 3 (see the comments there).

**Comment by sumancholleti** [comment]
Thanks much Estan,

also i see example pdfs is it done through APACHE FOP?

How do i add description after messgae, like lets say if  i need to add sample message under table in html,looks like /****/ adds before message table in html

**Comment by estan** [comment]
@sumancholleti That is currently not possible. A message has a single description, and in the default built-in templates, that description ends up before the field table for the message. If you want the description to go after the table, you'll have to make a custom table.

Since it seems you've solved the problem with running the tool on macOS, I'm closing this issue now.

**Comment by sumancholleti** [comment]
Thanks,

i can add custom table , but how do i get from mustache template because {{message description has only one message}}

**Comment by estan** [comment]
You can't, like I said, a message has a single description. So you have to choose: Either have the description above the field table or below it. There's no way to have two descriptions.

**Comment by sumancholleti** [comment]
Thank you
