### ISSUE TITLE
Mustache Template or custom Messages

### ISSUE THREAD

**Issue by sumancholleti** [estan/protoc-gen-doc#271]
Hello Estan,

if i need to add sample message under description how do i add or if i want to add some image how do i catch in template, like lets say

/*
*comment ABC
*/
i have 

message abc{
optional string id=1;
}
example message
abc{
[{id:0}]
}

some image i want to display in html

How do i add this in mustache 

i see we already have message{{message_description}} but its only printing commentABC

lets say if i need to add example messae in html after message field table or some image

how do i capture this in mustache, please let me know

**Comment by estan** [comment]
Mustache is just a template language, it only works with text and knows nothing about HTML, DocBook XML, Markdown et.c. So it doesn't have any tags for images.

What you could do is, in your custom Mustache template, disable HTML escaping (see Mustache docs). Then, in your description (in the `.proto` file), use a HTML `<img>` tag to insert the image. But this would only work for HTML output, so then the DocBook XML output would be wrong.

If you're only generating one format of your documentation, you could do this, but not if you want to be able to generate HTML, Markdown and DocBook :/ Sorry, but there's just no other way.

And regarding "after message field table", like I said, a message has only a single description which the plugin extracts from the `.proto`. You have to decide if it should go above or below the field table. There's no way to add a second description (e.g. have one description above and one below).

**Comment by sumancholleti** [comment]
Okay thank you

**Comment by sumancholleti** [comment]
Estan

would it be possible to use index of element in ur mustache template


I am trying to change scalarvaluetypes json and trying to access first element , is it possible, if i change that json and access in mustache template am not seeing new values that i changed in json

so 2 questions
1. how do i access first element in json
2. how do i see the changes in html that i made in json that you hve in templates folder

**Comment by estan** [comment]
1. I think Mustache has some syntax for accessing array elements by index (maybe `{{ some_array.1 }}`). You'll have to check the Mustache documentation.

2. The `scalar_value_types.json` file is embedded into the executable as a Qt resource, so you have to re-build the tool (`make clean && make`) for any changes to take effect.

**Comment by sumancholleti** [comment]
Thanks for reply.
I tried scalar_value_types.1 it didnt work , do you think u can help me with this

so if i change scalar_value_types.json

I need to run make clean and make?

**Comment by estan** [comment]
> Thanks for reply.
> I tried scalar_value_types.1 it didnt work , do you think u can help me with this

You'll have to look up the Mustache docs on how to do it. I'm not sure how it's done.

> so if i change scalar_value_types.json
> I need to run make clean and make?

Correct. That file is embedded into the executable as part of the compilation process, so re-building is required.

**Comment by sumancholleti** [comment]
okay thanks.
