### ISSUE TITLE
The new building is not take effect

### ISSUE THREAD

**Issue by freedom-diy** [estan/protoc-gen-doc#278]
step1. I'm forked this repository, and modify the **main.cpp**'s function which is using the single-line(//) documentation comments replace the origin single-line (///) documentation comments.

step2. I building a protoc-gen-doc file by my git source code.

step3. I try to generated the html, and it is success, but the documentation comments is not display.
```linux
sudo protoc-gen-doc --doc_out=html,proto.html:./ ./*.proto
```

Q1: How to modified the right code, thanks!
Background: My team's project have lots of proto file, and the comments is defined single-line(//).
```proto
message AddFinancialPlanSaleResponse
{
    optional    proto.basic.ResponseBasic   basic               = 1; //demo field
    optional    uint64                      sale_id             = 2;  //sold id
}
```

Here is my modified code:
```C++
while (!stream.atEnd()) {
        QString line = stream.readLine().trimmed();
        if (line.isEmpty()) {
            continue;
        } else if (line.startsWith("//")) {
            while (!stream.atEnd() && line.startsWith("//")) {
                description += line.mid(line.startsWith("// ") ? 3 : 2) + '\n';
                line = stream.readLine().trimmed();
            }
            description = description.left(description.size() - 1);
        } else if (line.startsWith("/**") && !line.startsWith("/***/")) {
            line = line.mid(2);
            int start, end;
            while ((end = line.indexOf("*/")) == -1) {
                start = 0;
                if (line.startsWith("*")) ++start;
                if (line.startsWith("* ")) ++start;
                description += line.mid(start) + '\n';
                line = stream.readLine().trimmed();
            }
            start = 0;
            if (line.startsWith("*") && !line.startsWith("*/")) ++start;
            if (line.startsWith("* ")) ++start;
            description += line.mid(start, end - start);
        }
        break;
    }
```

**Comment by silkentrance** [comment]
AFAIK you need to use three slashes for doc comments, e.g. /// demo field instead of just two.

**Comment by freedom-diy** [comment]
Hi silkentrance,

I know that origin "protoc-gen-doc" is used the three slashes for doc comments.

But our team have lots of doc comments is used the two slashes.

So my problem is that how to take effect for new building when I modified the main.app's code.

Thanks~

**Comment by silkentrance** [comment]
Wouldn't it be easier to just

```
sed -r -i 's,//([^/])(.*)$,///\1\2,' source.proto
```

replace existing double slashes by three slashes in your existing code?

I am asking because others already depend on the fact that two slashes will not be recognized as doc comments, allowing them to add additional line comments to the sources.

And of course, it would be much easier to modify the existing sources, which can be done automatically.

**Comment by freedom-diy** [comment]
Thank you for your patience! @silkentrance

**Comment by freedom-diy** [comment]
@silkentrance  `sed -r -i -e 's,//([^/])(.*)$,///\1\2,' -e 's,////([^/])(.*)$,///\1\2,' source.proto` 
This sed regular expressions is better then before.
