### ISSUE TITLE
Build Mac OS X .dmg on Travis CI

### ISSUE THREAD

**Issue by estan** [estan/protoc-gen-doc#5]
I think it should be possible. It seems you can install Qt using `brew install`.

**Comment by priyatam** [comment]
I installed protobuf and qt via brew, but still can't generate a protoc-gen-doc executable by running make. 

```
Project ERROR: This program requires Qt 5.x. (qmake error)
make: *** No targets specified and no makefile found.  Stop. (make)
```

Instead of building from source, can you attach the dmg onto the latest release?

**Comment by estan** [comment]
Hi @priyatam,

I unfortunately don't have a Mac myself. I did test building on Mac OS X at my school at one point, but that was quite some time ago (when I wrote the Mac OS X instructions in BUILDING.md). At that time, I did not use `brew` to install Qt. I think I used the installer from the Qt download pages.

It is true that protoc-gen-doc requires Qt 5. Did you perhaps install the `qt` package and not `qt5`?

**Comment by estan** [comment]
As I just started my last term at school this Monday, I could always see if I could build a .dmg at school and put it under releases. The problem is that I don't know if I could keep it updated. So to get consistent packaging for Mac OS X, then we'd need either 1) Someone with a Mac that does the building for each release. 2) Try to get building on Travis CI going.

**Comment by priyatam** [comment]
After installing qt5 from brew and running qmake and make I get this error

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -Wall -W -fPIC -DQT_NO_DEBUG -DQT_CORE_LIB -I. -I/xxx/protobuf/include -I/usr/local/Cellar/qt5/5.5.0/lib/QtCore.framework/Headers -I. -I/usr/local/Cellar/qt5/5.5.0/mkspecs/macx-clang -F/usr/local/Cellar/qt5/5.5.0/lib -o main.o src/main.cpp
src/main.cpp:35:10: fatal error: 'google/protobuf/compiler/plugin.h' file not found
#include <google/protobuf/compiler/plugin.h>
```

PROTOBUF_PREFIX is set to the the protobuf-folder/src.

**Comment by estan** [comment]
Hm. I'm not sure it should be set to the `src` subdirectory. Don't have time to check right now as I'm going to bed. Your `-I/xxx/protobuf/include` looks a bit strange. Is that really the path to the protobuf headers on your system?

**Comment by priyatam** [comment]
What directory should PROTOBUF_PREFIX point to? Please be specific as the full download from [protobuf](https://developers.google.com/protocol-buffers/) includes a root directory with 'src' as well as many other dirs. Pointing to src doesn't work.

**Comment by estan** [comment]
PROTOBUF_PREFIX should on Mac OS X point to the directory that contains an `include` directory. When I tried building on Mac OS X (I've only done this once), this was the top-level directory where I built the protobuf library (since I built it myself).

**Comment by priyatam** [comment]
There is no include directory in the official release. It's best if you not imagine what you did months ago, but rather point out to the latest or _a_ version of [protobuff](https://developers.google.com/protocol-buffers/) and its corresponding folder.

**Comment by estan** [comment]
I'm sorry. I was wrong about the `include` subdirectory. It should point to the `src` subdirectory as far as I remember. It's a bit problematic for me as I don't have access to a Mac, so the only think I can do is to to try to remember what I did when I tested it on a Mac. This was quite some time ago (when protobuf 2.5.0 was the latest version), and I only did it once. As far as I can remember, I

 * Downloaded the 2.5.0 source distribution [1] built it (using clang).
 * Set `PROTOBUF_PREFIX` to point to `/path/to/protobuf-2.5.0/src`. This should allow the build process to find the protobuf headers. Note that I think the instructions in `BUILDING.md` are wrong now that I look at them.  `PROTOBUF_PREFIX` should point to the `src` subdirectory.
 * Then built using `qmake && make`.

Note that I have never tried to build against packages installed from Homebrew (that's essentially what this issue is about), so that is unsupported at this point, and that I don't have easy access to a Mac, so I cannot test using more recent protobuf versions (I only think the version was 2.5.0 when I last tested, but that is from memory).

I'm sorry if you're frustrated, but this is all I can do, given what I have :( I'd be happy if someone with a Mac could get involved and do the necessary investigation on how to build on Mac OS X (using latest protobuf and Qt 5).

[1] https://github.com/google/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.gz

**Comment by estan** [comment]
No, sorry. I'm tired right now. Thinking further, I think I actually went ahead with the `make install` step after building protobuf, which should definitely produce an `include` directory rooted under the install prefix path. So I don't think the instructions are not wrong after all.

But as I said, I don't currently have access to a Mac, so I cannot verify that this is the case with current versions of protobuf (or with 2.5.0 either for that matter). I might be able to get access to a Mac at school again and do a quick check. If so I can get back to you. But it shouldn't be too hard to look at your installation of protobuf to see where the headers are installed.

**Comment by estan** [comment]
I also don't think this is the right issue to use for build problems on Mac. This issue is a TODO to get Mac OS X builds on Travis CI going. If there's a problem with the build instructions for Mac OS X per se, then that should be reported as a separate issue.

**Comment by estan** [comment]
I realize that the the build instructions are a little misleading. To clarify: The `/path/to/protobuf-2.6.1` in the build instructions represent the install path to which a built protobuf library was installed with `make install`. Such an installation path should definitely have an `include` subdirectory.

If you're installing protobuf from Homebrew, then I suspect `PROTOBUF_PREFIX` should be set to the installation prefix that Homebrew uses (not sure what that is), as that should have an `include` directory that contains the protobuf headers (e.g. `google/protobuf/compiler/plugin.h` et.c.).

On Tuesday I'll be in school, and I'll try to remember to stop by one of the Mac computer rooms and test building on Mac OS X one more time.

**Comment by estan** [comment]
@priyatam I've now tried another build again on Mac OS X (10.9.5) at my school. It worked fine.

Here's the steps I followed:

1. Download and install Qt 5.5.0 to `$HOME/Qt` using the Qt Online Installer.
2. Download, build and install protobuf 2.6.1 to `$HOME/protobuf`:

        curl -O -L https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
        tar xf protobuf-2.6.1.tar.gz
        cd protobuf-2.6.1
        CC=clang CXX=clang++ ./configure --prefix=$HOME/protobuf
        CC=clang CXX=clang++ make -j4
        make install

    Note that the last step is important. This is what installs the library and headers.

3. Download and build protoc-gen-doc in `$HOME/protoc-gen-doc`:

        git clone https://github.com/estan/protoc-gen-doc.git
        cd protoc-gen-doc
        export PROTOBUF_PREFIX=$HOME/protobuf
        ~/Qt/5.5/clang_64/bin/qmake
        make

The last step produces the `protoc-gen-doc` plugin binary `~/protoc-gen-doc/protoc-gen-doc`. You can test it on the included example `.proto` files like this:

    export PATH=$HOME/protoc-gen-doc:$PATH
    ~/protobuf/bin/protoc --doc_out=html,example.html:. examples/proto/*.proto

Which will produce the output `example.html`.

**Comment by estan** [comment]
Note that I haven't tried with Qt and protobuf from Homebrew, as I don't have the space required for the Qt build on my school account. However, supposing you have `/usr/local` as Homebrew installation prefix, then I think it should be as simple as:

    brew install qt5 protobuf
    git clone https://github.com/estan/protoc-gen-doc.git
    cd protoc-gen-doc
    export PROTOBUF_PREFIX=/usr/local
    qmake
    make

The `PROTOBUF_PREFIX` for the `protoc-gen-doc` build should be set to the installation prefix that Homebrew uses. Please tell me if it doesn't work, and we'll work from there.

**Comment by priyatam** [comment]
Thanks for the new instructions. Building protobuf from source did the trick. Oddly, the "download" link from google [protobuff](https://developers.google.com/protocol-buffers/)) and the git repo are not the same.

The best way to simplify the setup for OS X developers would be to automate the above steps in a hombrew formula: `brew install protoc-gen-doc`.

**Comment by estan** [comment]
Glad it worked out for you.

And absolutely, if someone with a Mac feels like taking on the task of writing and maintaining a Homebrew formula. That would be great.

Another plan would be to try to build a .dmg on Travis CI (what this issue was really about :) ).

**Comment by estan** [comment]
I've now added building on Mac OS X on Travis CI. Here's an example of the latest succeeding build: https://travis-ci.org/estan/protoc-gen-doc/jobs/101925327

I'll close this issue now, since I don't think I'll be able to do automatic creation of .dmg on Travis anytime soon. The test/feedback cycle is so slow when trying stuff out. If I get a Mac some time I'll reopen the issue.
