### ISSUE TITLE
Binary for centOS

### ISSUE THREAD

**Issue by vashibhavin** [estan/protoc-gen-doc#7]
I have been looking for a good protobuf documentation generator tool. Can you provide the binaries for centOS?

**Comment by estan** [comment]
Hi,

I'm not doing the distro packages manually, but using the Open Build Service. They do have support for building CentOS 6 and 7 packages, but unfortunately there's no way to enable any external repository (e.g. like the EPEL repositories), which would be required to get Qt 5 on there (and possibly also libprotobuf / libprotoc).

It should not be too much work to build the tool yourself, as long as you have a modern compiler, Qt 5 and libprotobuf / libprotoc.

I'll keep this issue open though, if someone comes along that could take care of providing CentOS packages.

**Comment by estan** [comment]
I could always see if I could build CentOS packages manually in a Docker container. But no guarantee on when I have time for that, as I'm a bit busy with work right now. Which CentOS release are you on?

**Comment by estan** [comment]
I had a quick look at what is provided by the EPEL repositories, and it seems the only combination that has the required version of `protobuf-devel` (>= 2.5.0) is CentOS 7 x64.

**Comment by estan** [comment]
I've now created an RPM for CentOS 7 x64 inside a Docker container. It's available for download in the [Releases](https://github.com/estan/protoc-gen-doc/releases) section. You can try it out with:

    curl -L -O https://github.com/estan/protoc-gen-doc/releases/download/v0.6/protoc-gen-doc-0.6-1.el7.centos.x86_64.rpm
    yum install -y epel-release
    yum install -y protoc-gen-doc-0.6-1.el7.centos.x86_64.rpm

If you already have the EPEL repository enabled, you don't need the first `yum` command.

Please let me know if it works out for you, and I'll close this issue. I tested the plugin from the RPM on the examples in the GitHub repo inside the Docker container, and it seems to work fine.

I'm unfortunately unable to make any packages for CentOS 6, as the `protobuf-devel` version in that EPEL repository is too old.

**Comment by vashibhavin** [comment]
Argh. CentOS 6.5. I have been planning to upgrade to centOS 7, let me see if

**Comment by estan** [comment]
No problem. If you find some CentOS 6 repository that provides a newer `protobuf-devel`, and you feel like trying to build your own RPM, these are the commands I used to build the CentOS 7 RPM:

    yum install -y epel-release 
    yum install -y protobuf-devel
    yum install -y qt5-qtbase-devel
    yum install -y gcc-c++
    yum install -y make
    yum install -y rpm-build
    mkdir -p /root/rpmbuild/SOURCES
    curl -L -o /root/rpmbuild/SOURCES/v0.6.tar.gz https://github.com/estan/protoc-gen-doc/archive/v0.6.tar.gz
    tar xf /root/rpmbuild/SOURCES/v0.6.tar.gz
    rpmbuild -bb protoc-gen-doc-0.6/pkg/protoc-gen-doc.spec

Which gives the RPM in `/root/rpmbuild/RPMS/x86_64/protoc-gen-doc-0.6-1.el7.centos.x86_64.rpm`. Though don't do it as `root` as I did, since it's highly advised against that. I didn't care as I did it in a Docker container with no fear of screwing things up.

Unfortunately don't have time to investigate a CentOS 6 package myself, even though I know many people are still on CentOS 6.

**Comment by vashibhavin** [comment]
No worries. Thanks for the response. I will play around with it to see if I can get something going.

**Comment by estan** [comment]
Alright. Let me know if you upgrade to CentOS 7 and get to test the RPM. I'll keep the issue open for a while in case you do that.

**Comment by estan** [comment]
I'm closing this now. Please re-open it in case there's a problem with the CentOS 7 RPM. CentOS 6 is unfortunately not possible due to old versions of the dependencies.

**Comment by estan** [comment]
If you've had the time to update to CentOS 7, I've now automated the CentOS 7 RPM generation a bit more, and set up a repository (x86_64 only) which you can use with:

    curl -o /etc/yum.repos.d/protoc-gen-doc.repo http://tinyurl.com/protoc-gen-doc-repo
    yum install -y epel-release
    yum install -y protoc-gen-doc
