### ISSUE TITLE
File exclusion of imports

### ISSUE THREAD

**Issue by rmartin7c** [estan/protoc-gen-doc#74]
We have google.protobuf.Empty (empty.proto) included in many of our files. We're using protobuf 3, but with proto2 syntax. This include from Google is in proto3 syntax, and contains options that reference plugins not available on all platforms. Therefore, we want to exclude it from documentation. There doesn't seem to be a way to flag an import statement as "don't follow" or "exclude." Can this feature be added?

**Comment by rmartin7c** [comment]
Omitting .proto files not in the proto_path would also be sufficient - that way, 3rd party includes could be left out simply by omitting them from the path.

**Comment by estan** [comment]
See my comment on #75 for why this is currently not possible :/
