### ISSUE TITLE
File exclusion should happen before parsing

### ISSUE THREAD

**Issue by rmartin7c** [estan/protoc-gen-doc#75]
As in issue #74: We have google.protobuf.Empty (empty.proto) included in many of our files. We're using protobuf 3, but with proto2 syntax. This include from Google is in proto3 syntax, and contains options that reference plugins not available on all platforms. Therefore, we want to exclude it from documentation. 

When we put ///@exclude at the top of the file, it was excluded from the documentation. However, the parser still crashed on syntax="proto3";. When we changed this to proto2, it then complained about unsupported options. We commented out options until the doc_out command ran successfully, and the file was excluded. Why is the parser insisting on parsing a file it's been instructed to exclude? Can we move the exclusion check earlier so that a file excluded due to incompatible syntax won't crash the whole job?

**Comment by estan** [comment]
Hi @rmartin7c,

Afraid I have some bad news. The parsing of the input `.proto` files is completely of the control of the plugin. The protoc compiler fully parses each input file, including following imports, before the plugin is even called. The result of the parsing is then fed to the plugin as `FileDescriptor` instances, which is what the plugin has to work with.

There's therefore no way for the plugin to make `@exclude` be a "true" exclusion, where the file is not even parsed. You'll have to wait until the plugin is updated to work with the compiler from protobuf 3 (see the [1.0 milestone](https://github.com/estan/protoc-gen-doc/milestones/protoc-gen-doc%20v1.0)). When that happens, you should be able to invoke the plugin through the protobuf 3 compiler, which should be able to cope with both 2 and 3 syntax.

To clarify: The way `@exclude` works is by looking for this tag in the output that the compiler feeds it, and if found, omit output for the tagged element. There's no way for a protobuf generator plugin to direct the parsing process to exclude certain files.

So sorry, but I don't think there's a way to fix this issue, or #74, short of rewriting this tool to no longer be a protobuf compiler plugin, but a custom tool that does all the parsing itself, which I'm not prepared to do at the moment :(

**Comment by rmartin7c** [comment]
I was reviewing your source, and I was afraid that this was going to be the answer. Disappointing, but not your fault. Any timeframe on the proto3 support?

**Comment by estan** [comment]
@rmartin7c: Yea, sorry!

No timeframe on the proto3 support, I was planning on waiting until protobuf 3 final has been released, but I guess I should start a little earlier in case it takes some time to get it done (I'm not actually using protobuf myself or at work at the moment). The thing that's really blocking the 1.0 release of the plugin at the moment is #22 , which I was hoping could be solved through some input from the protobuf devs, but looking at the lack of answers to my closing comment on [this issue](https://github.com/google/protobuf/issues/1385) and my [thread here](https://groups.google.com/forum/#!topic/protobuf/KxbvItIKz1k) I'm not too hopeful.

But yea, I should start on protobuf 3 support before it is released anyway. I do take PRs of course :) (but it's important also that the plugin keeps working with protobuf 2).

**Comment by estan** [comment]
BTW, follow #17 for updates on when protobuf 3 support gets moving.

**Comment by estan** [comment]
Until then, as a workaround, perhaps you could add some pre-processing step to your doc generation that strips the import of the proto3-syntaxed file. Not too pretty I know, but as a stop-gap solution.

**Comment by rmartin7c** [comment]
@estan I wish I were in a position to supply a PR, but I'm afraid that my C++ is years rusty, and I'm not at all familiar with QT5 or the Protoc internals. I'd be happy to serve as a tester, though, if you have any pre-release code you'd like feedback on.

**Comment by estan** [comment]
Alright. Yea I should at least have a look what changes are needed for proto3 soon, I'm not even sure of which they ae. Maybe it's not so much at all (from this plugin's point of view I mean).

**Comment by rmartin7c** [comment]
AFAIK they haven't changed the comment syntax at all.

**Comment by cmorent** [comment]
Hey @estan, is there any update on this ? Thanks in advance !

**Comment by estan** [comment]
@cmorent I'm no longer the maintainer for this project. The current maintainer is @pseudomuto, which has ported the plugin from C++ to Go. So it's all new code and he's in a better position to answer what it would take to fix this bug.

**Comment by cmorent** [comment]
Oh sorry ! And thanks for your quick answer !
